import devinImage from "@/public/devin.jpg";
import Image from "next/image";


export const metadata = {
  title: "home page",
  description: "Generated by create next app",
};

//import kore nile width hight dite hoy na

export default function Home() {
  return (
    <div>
      <h1>Next.js Image Optimization</h1>

      <div className="mt-4 relative w-[800px] h-[400px] border-2 border-teal-300 overflow-hidden">
        <Image
        // placeholder="blur"
          fill
          src={devinImage}
          // src="https://img.youtube.com/vi/NgrljB7UU34/maxresdefault.jpg"
          alt="Will devin replace Programmers?"
          className="object-cover"
        />
      </div>
    </div>
  );
}
